[from-internal-pixel-sms]
exten => _.,1,NoOp(Outbound SMS from ${CHANNEL(endpoint)} to ${EXTEN})
 same => n,Set(SRC=${CHANNEL(endpoint)})
 same => n,GotoIf($["${SRC}" = ""]?invalid)
 same => n,GotoIf($["${DB(SIP/sms/${SRC})}" != "1"]?invalid)
 same => n,Set(GW=${DB(SIP/extgw/${SRC})})
 same => n,GotoIf($["${GW}" = ""]?invalid)
 same => n,Set(SMS_NUMBER=${FILTER(0-9+,${EXTEN})})
 same => n,GotoIf($[${LEN(${SMS_NUMBER})} < 10]?invalid)
 same => n,GotoIf($[${LEN(${SMS_NUMBER})} > 15]?invalid)
 same => n,Set(MESSAGE(body)=SMS ${SMS_NUMBER}: ${MESSAGE(body)})
 same => n,MessageSend(pjsip:${GW},sip:${SRC}@sip.elfradio.net,sip:${GW}@sip.elfradio.net)
 same => n,NoOp(Outbound SMS submit status: ${MESSAGE_SEND_STATUS})
 same => n,Hangup()
 same => n(invalid),NoOp(Rejected outbound SMS)
 same => n,Hangup()

[from-pixel-sms]
exten => _.,1,NoOp(Inbound SMS on gateway ${CHANNEL(endpoint)})
 same => n,Set(GW=${CHANNEL(endpoint)})
 same => n,Set(DST=${DB(SIP/gwsms/${GW})})
 same => n,GotoIf($["${DST}" = ""]?invalid)
 same => n,Set(GSM_SMS_SENDER=${FILTER(0-9+,${MESSAGE_DATA(X-GSM-CallerID)})})
 same => n,GotoIf($[${LEN(${GSM_SMS_SENDER})} < 6]?invalid)
 same => n,GotoIf($[${LEN(${GSM_SMS_SENDER})} > 16]?invalid)
 same => n,Set(SIP_SMS_SENDER=${GSM_SMS_SENDER})
 same => n,GotoIf($["${GSM_SMS_SENDER:0:3}" = "+61" & ${LEN(${GSM_SMS_SENDER})} = 12]?australia)
 same => n,GotoIf($["${GSM_SMS_SENDER:0:3}" = "+86" & ${LEN(${GSM_SMS_SENDER})} = 14]?china)
 same => n,Goto(send)
 same => n(australia),Set(SIP_SMS_SENDER=0${GSM_SMS_SENDER:3})
 same => n,Goto(send)
 same => n(china),Set(SIP_SMS_SENDER=${GSM_SMS_SENDER:3})
 same => n(send),MessageSend(pjsip:${DST},sip:${SIP_SMS_SENDER}@sip.elfradio.net,sip:${DST}@sip.elfradio.net)
 same => n,NoOp(Inbound SMS submit status ${MESSAGE_SEND_STATUS} to ${DST})
 same => n,Hangup()
 same => n(invalid),NoOp(Rejected inbound SMS)
 same => n,Hangup()
