[sms-sip-user]
exten => s,1,Set(LOCAL(raw)=${MESSAGE(from)})
 same => n,Set(LOCAL(raw)=${CUT(raw,@,1)})
 same => n,Set(LOCAL(raw)=${CUT(raw,:,2)})
 same => n,Set(GOSUB_RETVAL=${FILTER(0-9,${raw})})
 same => n,Return()

[from-internal-pixel-sms]
exten => _.,1,NoOp(Outbound SMS from ${MESSAGE(from)} to ${EXTEN})
 same => n,Set(SRC=${CHANNEL(endpoint)})
 same => n,ExecIf($["${SRC}" = ""]?Gosub(sms-sip-user,s,1))
 same => n,ExecIf($["${SRC}" = ""]?Set(SRC=${GOSUB_RETVAL}))
 same => n,Verbose(0, SMS out from=${MESSAGE(from)} SRC=${SRC} exten=${EXTEN})
 same => n,GotoIf($["${SRC}" = ""]?invalid)
 same => n,GotoIf($["${DB(SIP/sms/${SRC})}" != "1"]?invalid)
 same => n,Set(GW=${DB(SIP/extgw/${SRC})})
 same => n,GotoIf($["${GW}" = ""]?invalid)
 same => n,Set(SMS_NUMBER=${FILTER(0-9+,${EXTEN})})
 same => n,GotoIf($[${LEN(${SMS_NUMBER})} < 10]?invalid)
 same => n,GotoIf($[${LEN(${SMS_NUMBER})} > 15]?invalid)
 same => n,Set(MESSAGE(body)=SMS ${SMS_NUMBER}: ${MESSAGE(body)})
 same => n,MessageSend(pjsip:${GW},sip:${SRC}@sip.elfradio.net,sip:${GW}@sip.elfradio.net)
 same => n,Verbose(0, SMS out SRC=${SRC} GW=${GW} NUM=${SMS_NUMBER} status=${MESSAGE_SEND_STATUS})
 same => n,Hangup()
 same => n(invalid),Verbose(0, SMS out rejected SRC=${SRC} exten=${EXTEN})
 same => n,Hangup()

[from-pixel-sms]
exten => _.,1,NoOp(Inbound SMS from ${MESSAGE(from)})
 same => n,Set(GW=${CHANNEL(endpoint)})
 same => n,ExecIf($["${GW}" = ""]?Gosub(sms-sip-user,s,1))
 same => n,ExecIf($["${GW}" = ""]?Set(GW=${GOSUB_RETVAL}))
 same => n,Verbose(0, SMS in from=${MESSAGE(from)} GW=${GW})
 same => n,GotoIf($[${LEN(${GW})} < 3]?invalid)
 same => n,GotoIf($[${LEN(${GW})} > 6]?invalid)
 same => n,GotoIf($["${DB(SIP/is_gw/${GW})}" != "1"]?invalid)
 same => n,Set(DST=${DB(SIP/gwsms/${GW})})
 same => n,GotoIf($["${DST}" = ""]?invalid)
 same => n,GotoIf($["${DB(SIP/sms/${DST})}" != "1"]?invalid)
 same => n,Set(GSM_SMS_SENDER=${FILTER(0-9+,${MESSAGE_DATA(X-GSM-CallerID)})})
 same => n,GotoIf($[${LEN(${GSM_SMS_SENDER})} < 6]?invalid)
 same => n,GotoIf($[${LEN(${GSM_SMS_SENDER})} > 16]?invalid)
 same => n,Set(SIP_SMS_SENDER=${GSM_SMS_SENDER})
 same => n,GotoIf($["${GSM_SMS_SENDER:0:3}" = "+61" & ${LEN(${GSM_SMS_SENDER})} = 12]?australia)
 same => n,GotoIf($["${GSM_SMS_SENDER:0:3}" = "+86" & ${LEN(${GSM_SMS_SENDER})} = 14]?china)
 same => n,Goto(send)
 same => n(australia),Set(SIP_SMS_SENDER=0${GSM_SMS_SENDER:3})
 same => n,Goto(send)
 same => n(china),Set(SIP_SMS_SENDER=${GSM_SMS_SENDER:3})
 same => n(send),MessageSend(pjsip:${DST},sip:${SIP_SMS_SENDER}@sip.elfradio.net,sip:${DST}@sip.elfradio.net)
 same => n,Verbose(0, SMS in GW=${GW} DST=${DST} status=${MESSAGE_SEND_STATUS})
 same => n,Hangup()
 same => n(invalid),Verbose(0, SMS in rejected from=${MESSAGE(from)} GW=${GW} DST=${DST})
 same => n,Hangup()
