[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=217.142.229.125
external_signaling_address=217.142.229.125
allow_reload=yes
local_net=10.0.0.0/24

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_media_address=217.142.229.125
external_signaling_address=217.142.229.125
allow_reload=yes
local_net=10.0.0.0/24

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
external_media_address=217.142.229.125
external_signaling_address=217.142.229.125
ca_list_file=/etc/ssl/certs/ca-certificates.crt
cert_file=/etc/asterisk/keys/sip.elfradio.net-fullchain.crt
priv_key_file=/etc/asterisk/keys/sip.elfradio.net.key
method=sslv23
verify_client=no
verify_server=no
allow_reload=yes
local_net=10.0.0.0/24
