[global]
type=global
user_agent=elfradio-sip
endpoint_identifier_order=username,ip
default_realm=asterisk

[system]
type=system

#include pjsip.transports.conf
#include pjsip.aor.conf
#include pjsip.auth.conf
#include pjsip.endpoint.conf
