listener 8883 0.0.0.0
protocol mqtt
allow_anonymous false
password_file /etc/mosquitto/elfremote/passwords
acl_file /etc/mosquitto/elfremote/acl
certfile /etc/mosquitto/elfremote/fullchain.pem
keyfile /etc/mosquitto/elfremote/privkey.pem
tls_version tlsv1.2
max_connections 100
max_packet_size 8192
message_size_limit 4096
max_queued_messages 100
persistent_client_expiration 7d
